### ISSUE TITLE
How can I run this project?

### ISSUE THREAD

**Issue by kenshinji** [spilth/maven-book#1]
Hello, thanks for sharing such a amazing book. I am kind of a newbie to Ruby and Rails stuff. So may I ask how can I run this project in order to generate the book? Thanks , again.

**Comment by spilth** [comment]
I updated the README with instructions: https://github.com/spilth/maven-book

You can also just view https://github.com/spilth/maven-book/blob/master/src/pragmatic-guide-to-maven.md

**Comment by kenshinji** [comment]
Thanks :) really appreciate it.
